#------------------------------------#
         #PLUGIN BY ItzMeFahri#
             #SUBSCRIBE
      #CHANELL ItzMeFahri
#------------------------------------#


#Use "\n" To add Line
#Use § To add color
#------------------------------
#Title
Title: "§e§b<<<§dGAMEMODE§e§b>>>"
#------------------------------
#Content
Content: "Plis edit config.yml"
#------------------------------